# docker-compose.offline.yml
services:

  extract-icsi:
    image: python:3.11
    network_mode: "host"
    volumes:
      - blockdata:/data
      - ./etl:/etl:ro
    working_dir: /data/raw
    command: ["bash", "/etl/01_extract_icsi.sh"]

  transcribe:
    image: python:3.11
    network_mode: "host"
    volumes:
      - blockdata:/data
      - ./etl:/etl:ro
    working_dir: /etl
    entrypoint: ["bash", "/etl/02_transcribe_whisper.sh"]
    environment:
      - DEBIAN_FRONTEND=noninteractive


  build-faiss:
    image: python:3.11
    network_mode: "host"
    volumes:
      - blockdata:/data
      - ./etl:/etl:ro
    working_dir: /data
    command: >
      bash -xc "
        pip install --no-cache-dir faiss-cpu sentence-transformers numpy &&
        python /etl/03_build_faiss.py
      "

  push-to-object:
    image: rclone/rclone:latest
    env_file: .env
    network_mode: "host"
    volumes:
      - blockdata:/mnt/block
    entrypoint: ["rclone"]
    command:
      - copy
      - /mnt/block/faiss_base
      - "${RCLONE_REMOTE}:${RCLONE_CONTAINER}/faiss_base"
      - --progress

volumes:
  blockdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/block