services:

  extract-data:
    image: python:3.11-slim
    working_dir: /data
    volumes:
      - /mnt/block:/data
      - ./extract-data.sh:/data/extract-data.sh:ro
      - ./wget.txt:/data/wget.txt:ro
    entrypoint: ["bash","/data/extract-data.sh"]


  transform-data:
    image: python:3.11-slim
    working_dir: /data
    volumes:
      - /mnt/block:/data
      - ./transform-data.sh:/data/transform-data.sh:ro
    entrypoint: ["bash","/data/transform-data.sh"]

  load-data:
    image: rclone/rclone:latest
    working_dir: /data
    environment:
      RCLONE_CONTAINER: object-persist-project39
    volumes:
      - /mnt/block:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
      - ./load-data.sh:/data/load-data.sh:ro
    entrypoint: ["sh","/data/load-data.sh"]
