# Base image with Python and required tools
FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
USER ${NB_UID}

# Install dependencies
RUN apt-get update && \
    apt-get install -y wget ffmpeg bash curl build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install pip packages
RUN pip install --upgrade pip && \
    pip install --pre --no-cache-dir setuptools wheel vosk && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Copy bash scripts into the container
COPY download_signals.sh ./download_signals.sh
COPY setup_env.sh ./setup_env.sh
COPY demovideo.MP4 ./demovideo.MP4

# Make scripts executable
RUN chmod +x download_signals.sh setup_env.sh

# Run the signal downloader first, then environment setup
CMD ./download_signals.sh && ./setup_env.sh && tail -f /dev/null
