global:
  scrape_interval: 5m
  scrape_timeout: 1m
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['129.114.27.22:8002']
  - job_name: 'backend-canary'
    static_configs:
      - targets: ['129.114.27.22:8001']
