global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8002']
  - job_name: 'backend-canary'
    static_configs:
      - targets: ['backend-canary:8001']
