services:

  ## ─── 1. EXTRACT ICSI SIGNALS + ANNOTATIONS ───────────────────────
  extract-icsi:
    image: python:3.11
    user: root
    volumes:
      - /mnt/block:/data
    working_dir: /data/raw
    command: >
      bash -c "
        set -e

        # 1. Download ICSI audio (signals)
        mkdir -p icsi/audio
        bash /app/etl/extract/icsiBuild-143922-Sun-May-11-2025.wget.sh \
          --dest icsi/audio

        # 2. Download core+contrib annotations (NXT format)
        mkdir -p icsi/annotations_plus
        wget -O icsi/annotations_plus/ICSI_plus_NXT.zip \
          https://groups.inf.ed.ac.uk/ami/ICSICorpusAnnotations/ICSI_plus_NXT.zip
        unzip -q icsi/annotations_plus/ICSI_plus_NXT.zip \
          -d icsi/annotations_plus
      "

  ## ─── 2. EXTRACT & UNPACK SLIDESPeeCH VIDEO ────────────────────────
  extract-video:
    image: python:3.11
    user: root
    volumes:
      - /mnt-block:/data
    working_dir: /data/raw/video
    command: >
      bash -c "
        set -e
        mkdir -p train_video
        wget -O train_video.tar.gz \
          https://speech-lab-share-data.oss-cn-shanghai.aliyuncs.com/SlideSpeech/train_video.tar.gz
        tar -xzf train_video.tar.gz -C train_video --strip-components=1
        rm train_video.tar.gz
      "

  ## ─── 3. CONVERT VIDEO → AUDIO ────────────────────────────────────
  convert-video:
    image: python:3.11
    user: root
    volumes:
      - /mnt-block:/data
    working_dir: /app/etl/extract
    depends_on:
      - extract-video
    command: >
      python convert_video_audio.py \
        --src /data/raw/video/train_video \
        --dst /data/raw/video/audio

  ## ─── 4. TRANSCRIBE ICSI AUDIO ────────────────────────────────────
  transcribe-icsi:
    build:
      context: ./transform
      dockerfile: Dockerfile.whisper
    user: root
    volumes:
      - whisper-cache:/root/.cache/whisper   # persists downloaded models
    working_dir: /app/etl/transform
    env_file:
      - ./.env
    depends_on:
      - extract-icsi
    command: >
      python transcribe.py \
        --audio_dir /data/raw/icsi/audio \
        --out /data/processed/transcripts_icsi.jsonl

  ## ─── 5. TRANSCRIBE VIDEO AUDIO ──────────────────────────────────
  transcribe-video:
    image: python:3.11
    user: root
    volumes:
      - /mnt-block:/data
    working_dir: /app/etl/transform
    env_file:
      - ./.env
    depends_on:
      - convert-video
    command: >
      python transcribe.py \
        --audio_dir /data/raw/video/audio \
        --out /data/processed/transcripts_video.jsonl

  ## ─── 6. BUILD + SPLIT CHUNKS ────────────────────────────────────
  build-chunks:
    image: python:3.11
    user: root
    volumes:
      - /mnt-block:/data
    working_dir: /app/etl/transform
    depends_on:
      - transcribe-icsi
      - transcribe-video
    command: >
      python build_chunks.py \
        --transcripts /data/processed/transcripts_icsi.jsonl,/data/processed/transcripts_video.jsonl \
        --icsi_txt /data/raw/icsi \
        --video_dir /data/raw/video \
        --annotations_plus /data/raw/icsi/annotations_plus \
        --out /data/processed/chunks.jsonl \
        --splits_cfg splits.yaml

  ## ─── 7. EMBED & INDEX ──────────────────────────────────────────
  embed-index:
    image: python:3.11
    user: root
    volumes:
      - /mnt-block:/data
    working_dir: /app/etl/transform
    depends_on:
      - build-chunks
    command: >
      python embed_and_index.py \
        --chunks /data/processed/chunks.jsonl \
        --index_dir /data/faiss_base

  ## ─── 8. BACKUP INDEX → OBJECT STORE ─────────────────────────────
  push-object:
    image: rclone/rclone:latest
    volumes:
      - /mnt-block:/data
    environment:
      RCLONE_REMOTE: chi_tacc
      RCLONE_CONTAINER: object-persist-project39
      RCLONE_CONFIG_CHI_TACC_TYPE: swift
      RCLONE_CONFIG_CHI_TACC_USER_ID: am15111@nyu.edu
      RCLONE_CONFIG_CHI_TACC_APPLICATION_CREDENTIAL_ID: 1e6a5c3039254b99a536ab3737779252
      RCLONE_CONFIG_CHI_TACC_APPLICATION_CREDENTIAL_SECRET: au2ccPLw7eMYNu2_wVT1hEd3UOoF9N51MfYLDk0gARphMyJkk7BhBoy0X1gsScT0Ge6cU8deY5X_QilOh-_2ng
      RCLONE_CONFIG_CHI_TACC_AUTH: https://chi.tacc.chameleoncloud.org:5000/v3
      RCLONE_CONFIG_CHI_TACC_REGION: CHI@TACC
    entrypoint: /bin/sh
    command: >
      -c "rclone copy /data/faiss_base $RCLONE_REMOTE:$RCLONE_CONTAINER/faiss_base --progress"

volumes:
  whisper-cache: